-- One-time migration: loads the 12 existing products from data/products.json into Supabase.
-- Run in Supabase SQL Editor AFTER schema.sql has been applied.
-- Media src paths are left pointing at the existing GitHub Pages assets/ folder — no re-upload needed yet.

INSERT INTO products (id, category, featured, status, sort_order, data) VALUES

('letter-keychain', 'keychains', true, 'active', 1, $json$
{"id":"letter-keychain","name":"Initial Letter Keychain","category":"keychains","tags":["keychains","gifts"],"price":100,"featured":true,"customizable":true,"customLabel":"Preferred initial / letter","badge":"Bestseller","description":"A tiny, precious world — dried petals and gold flakes suspended in a resin initial you carry everywhere. A piece of the garden, always with you.","specs":[["Size","3 inches approx."],["Material","Crystal-clear epoxy resin"],["Inclusions","Dried florals + gold leaf"],["Personalisation","Any single initial (A-Z)"]],"media":[{"type":"image","src":"assets/images/products/letter keychain/IMG-20260705-WA0099.jpg"},{"type":"image","src":"assets/images/products/letter keychain/IMG-20260705-WA0100.jpg"},{"type":"video","src":"assets/images/products/letter keychain/VID-20260705-WA0102.mp4"},{"type":"video","src":"assets/images/products/letter keychain/VID-20260705-WA0106.mp4"}]}
$json$::jsonb),

('photo-keychain', 'keychains', true, 'active', 2, $json$
{"id":"photo-keychain","name":"Photo Keychain","category":"keychains","tags":["keychains","gifts"],"price":200,"featured":true,"customizable":true,"customLabel":"Photo to set inside","description":"Your favourite photograph, sealed in resin and framed in gold flakes — the people you love, kept close on every set of keys.","specs":[["Size","3 inches approx."],["Material","Crystal-clear epoxy resin"],["Inclusions","Your printed photo + gold leaf"],["Personalisation","Any single photo"]],"media":[{"type":"image","src":"assets/images/products/photo key chain/IMG-20260705-WA0095.jpg"},{"type":"image","src":"assets/images/products/photo key chain/IMG-20260705-WA0096.jpg"},{"type":"image","src":"assets/images/products/photo key chain/IMG-20260705-WA0097.jpg"},{"type":"image","src":"assets/images/products/photo key chain/IMG-20260705-WA0101.jpg"},{"type":"video","src":"assets/images/products/photo key chain/VID-20260705-WA0103.mp4"}]}
$json$::jsonb),

('varmala-frame', 'frames', true, 'active', 3, $json$
{"id":"varmala-frame","name":"Varmala Preservation Frame","category":"frames","tags":["frames","preservation"],"price":1700,"featured":true,"customizable":true,"customLabel":"Reference photo of your varmala","badge":"Wedding favourite","description":"Your wedding varmala, arranged and cast in resin, set inside a handcrafted frame to hang as a keepsake of the day it all began. Choose from two frame designs.","specs":[["Size","10 inch"],["Features","With stand"],["Frame Material","Premium teakwood"],["Finish","Crystal-clear epoxy resin"]],"variants":{"type":"Design","options":[{"value":"Frame 1","media":[{"type":"image","src":"assets/images/products/frame 1 varamal preservation (10 inches)/IMG-20260705-WA0032.jpg"},{"type":"image","src":"assets/images/products/frame 1 varamal preservation (10 inches)/IMG-20260705-WA0051.jpg"},{"type":"image","src":"assets/images/products/frame 1 varamal preservation (10 inches)/IMG-20260705-WA0052.jpg"},{"type":"image","src":"assets/images/products/frame 1 varamal preservation (10 inches)/IMG-20260705-WA0053.jpg"}]}]},"media":[{"type":"image","src":"assets/images/products/frame 1 varamal preservation (10 inches)/IMG-20260705-WA0032.jpg"}]}
$json$::jsonb),

('deep-cast', 'preservation', true, 'active', 4, $json$
{"id":"deep-cast","name":"Deep Cast Preservation","category":"preservation","tags":["preservation","gifts"],"price":5000,"featured":true,"customizable":true,"customLabel":"Reference photo of your flowers","badge":"Signature","description":"A deep resin block that lets your flowers float at different depths inside the cast — a three-dimensional window into your most sentimental moment, mounted in premium teakwood.","specs":[["Size","9x12 inch"],["Depth","35 mm"],["Frame Material","Teakwood"],["Finish","Crystal-clear epoxy resin"]],"media":[{"type":"image","src":"assets/images/products/deep cast varmala preservation/deep cast 1.jpg"},{"type":"image","src":"assets/images/products/deep cast varmala preservation/deep cast.jpg"},{"type":"video","src":"assets/images/products/deep cast varmala preservation/VID-20260705-WA0063.mp4"},{"type":"video","src":"assets/images/products/deep cast varmala preservation/VID-20260705-WA0080.mp4"},{"type":"video","src":"assets/images/products/deep cast varmala preservation/VID-20260705-WA0081.mp4"},{"type":"video","src":"assets/images/products/deep cast varmala preservation/VID-20260705-WA0082.mp4"}]}
$json$::jsonb),

('full-varmala', 'preservation', true, 'active', 5, $json$
{"id":"full-varmala","name":"Full Varmala Preservation","category":"preservation","tags":["preservation"],"price":5000,"featured":true,"customizable":true,"customLabel":"Reference photo of your varmala","description":"Semi deep preservation with acrylic slidders. The full wedding garland — without breaking a single bloom — preserved intact and cast in crystal-clear resin.","specs":[["Size","12x18 inch"],["Material","Crystal-clear epoxy resin"],["Preservation","Full intact garland"],["Features","Acrylic sliders"]],"media":[{"type":"image","src":"assets/images/products/Full varmala preservation/IMG-20260705-WA0054.jpg"},{"type":"image","src":"assets/images/products/Full varmala preservation/IMG-20260705-WA0055.jpg"},{"type":"image","src":"assets/images/products/Full varmala preservation/IMG-20260705-WA0056.jpg"},{"type":"video","src":"assets/images/products/Full varmala preservation/VID-20260705-WA0057.mp4"}]}
$json$::jsonb),

('3d-block', 'preservation', true, 'active', 6, $json$
{"id":"3d-block","name":"Varmala Preservation — 3D Block","category":"preservation","tags":["preservation","gifts"],"price":2500,"featured":true,"customizable":true,"customLabel":"Reference photo of your flowers","description":"A three-dimensional resin block with flowers suspended at layered depths — a solid, sculptural keepsake that catches the light from every angle.","specs":[["Size","6.5 inches"],["Material","Crystal-clear epoxy resin"],["Style","Layered 3D suspension"]],"media":[{"type":"image","src":"assets/images/products/varamal preservation 3D block/IMG-20260705-WA0022.jpg"},{"type":"image","src":"assets/images/products/varamal preservation 3D block/IMG-20260705-WA0023.jpg"},{"type":"image","src":"assets/images/products/varamal preservation 3D block/IMG-20260705-WA0024.jpg"},{"type":"image","src":"assets/images/products/varamal preservation 3D block/IMG-20260705-WA0025.jpg"}]}
$json$::jsonb),

('love-letter', 'preservation', true, 'active', 7, $json$
{"id":"love-letter","name":"Love Letter & Rose Preservation","category":"preservation","tags":["preservation","gifts"],"price":1800,"featured":true,"customizable":true,"customLabel":"Your letter + note","description":"Words and petals, together forever. A handwritten letter and a rose sealed side by side in warm resin — preserved the way the moment felt.","specs":[["Size","9x12 inch"],["Material","Crystal-clear epoxy resin"],["Inclusions","Handwritten letter + rose"]],"media":[{"type":"image","src":"assets/images/products/love letter/IMG-20260705-WA0064.jpg"},{"type":"image","src":"assets/images/products/love letter/IMG-20260705-WA0065.jpg"}],"variants":{"type":"Option","options":[{"value":"Without Stand","price":1800},{"value":"With Stand","price":1900}]}}
$json$::jsonb),

('flower-preservation', 'preservation', false, 'active', 8, $json$
{"id":"flower-preservation","name":"Flower Preservation Wooden Frame","category":"preservation","tags":["preservation","gifts"],"price":2100,"featured":false,"customizable":true,"customLabel":"Reference photo of your flowers","description":"Delicate dried blooms sealed forever in warm amber resin. A timeless way to hold on to what once bloomed.","specs":[["Size","10 inch"],["Material","Crystal-clear epoxy resin"],["Inclusions","Dried florals"],["Features","With Stand"]],"media":[{"type":"image","src":"assets/images/products/flower preservation/IMG-20260705-WA0058.jpg"},{"type":"image","src":"assets/images/products/flower preservation/IMG-20260705-WA0059.jpg"}]}
$json$::jsonb),

('geode-clock', 'resin-art', true, 'active', 9, $json$
{"id":"geode-clock","name":"Resin Geode Wall Clock","category":"resin-art","tags":["resin-art","gifts"],"price":3000,"featured":true,"customizable":false,"description":"A statement wall clock that doubles as a geode painting. Layers of amber, sage, and rose resin build a gemstone landscape that marks every hour beautifully.","specs":[["Size","18x16 inch approx."],["Material","Resin on wood base"],["Mechanism","Silent sweep quartz"]],"media":[{"type":"image","src":"assets/images/products/resin geode clock/IMG-20260705-WA0035.jpg"},{"type":"image","src":"assets/images/products/resin geode clock/IMG-20260705-WA0037.jpg"},{"type":"image","src":"assets/images/products/resin geode clock/IMG-20260705-WA0042.jpg"},{"type":"video","src":"assets/images/products/resin geode clock/VID-20260705-WA0039.mp4"}]}
$json$::jsonb),

('beach-clock', 'resin-art', true, 'active', 10, $json$
{"id":"beach-clock","name":"Resin Beach Theme Clock","category":"resin-art","tags":["resin-art","gifts"],"price":2000,"featured":true,"customizable":false,"description":"Ocean waves, shells, and sand — all suspended in resin and working as your clock. For those who carry the coast wherever they go.","specs":[["Size","14 inch (can be customized)"],["Material","Resin on wood base"],["Mechanism","Silent sweep quartz"]],"media":[{"type":"image","src":"assets/images/products/resin beach clock/IMG-20260705-WA0026.jpg"},{"type":"image","src":"assets/images/products/resin beach clock/IMG-20260705-WA0027.jpg"},{"type":"image","src":"assets/images/products/resin beach clock/IMG-20260705-WA0028.jpg"},{"type":"image","src":"assets/images/products/resin beach clock/IMG-20260705-WA0029.jpg"},{"type":"image","src":"assets/images/products/resin beach clock/IMG-20260705-WA0030.jpg"}]}
$json$::jsonb),

('nameplate', 'resin-art', false, 'active', 11, $json$
{"id":"nameplate","name":"Resin Nameplate","category":"resin-art","tags":["resin-art","gifts"],"price":2000,"featured":false,"customizable":true,"customLabel":"Name / text for the plate","description":"A handcrafted resin nameplate with botanical inclusions and warm amber swirls — a personalised welcome at your door, unlike anything mass-produced.","specs":[["Size","14 inch"],["Material","Resin on wood base"],["Personalisation","Your name / family name"]],"media":[{"type":"image","src":"assets/images/products/resin nameplate/IMG-20260705-WA0047.jpg"},{"type":"image","src":"assets/images/products/resin nameplate/IMG-20260705-WA0050.jpg"},{"type":"video","src":"assets/images/products/resin nameplate/VID-20260705-WA0044.mp4"}]}
$json$::jsonb),

('resin-toran', 'resin-art', false, 'active', 12, $json$
{"id":"resin-toran","name":"Resin Toran","category":"resin-art","tags":["resin-art","gifts"],"price":3200,"featured":false,"customizable":false,"description":"A traditional toran reimagined in resin — marigolds, roses, and mango leaves preserved and hung at your doorway as a permanent blessing. A festive piece that lives forever.","specs":[["Size","36x7 inch"],["Base","MDF"],["Material","Crystal-clear epoxy resin"],["Occasion","Festive doorway decor"]],"variants":{"type":"Color","options":[{"value":"Golden Orange","media":[{"type":"image","src":"assets/images/products/resin toran golden orange/IMG-20260705-WA0085.jpg"},{"type":"image","src":"assets/images/products/resin toran golden orange/IMG-20260705-WA0086.jpg"},{"type":"image","src":"assets/images/products/resin toran golden orange/Resin toran.jpg"}]},{"value":"Purple","media":[{"type":"image","src":"assets/images/products/resin toran purple/IMG-20260705-WA0090.jpg"},{"type":"image","src":"assets/images/products/resin toran purple/IMG-20260705-WA0092.jpg"}]}]},"media":[{"type":"image","src":"assets/images/products/resin toran golden orange/IMG-20260705-WA0085.jpg"}]}
$json$::jsonb);
